SyncCursorPage[RunStep](
    data=[
        RunStep(
            id="step_ZtjkTzVJzfcCTlbYkBeTFrdQ",
            assistant_id="asst_tSLPn8dgt6pFmjL4jFJJiZtf",
            cancelled_at=None,
            completed_at=1700629114,
            created_at=1700629108,
            expired_at=None,
            failed_at=None,
            last_error=None,
            metadata=None,
            object="thread.run.step",
            run_id="run_PTbxCaHf9XLXvcK5kFkUNDKb",
            status="completed",
            step_details=MessageCreationStepDetails(
                message_creation=MessageCreation(
                    message_id="msg_yatvGpezCs3XzrSJulqRMXeR"
                ),
                type="message_creation",
            ),
            thread_id="thread_Yw9AKdgjsQ5WjEKnXAL5NhBC",
            type="message_creation",
            expires_at=None,
        ),
        RunStep(
            id="step_bbfaNruNeiEJTbWUvwdbesKL",
            assistant_id="asst_tSLPn8dgt6pFmjL4jFJJiZtf",
            cancelled_at=None,
            completed_at=1700629108,
            created_at=1700629105,
            expired_at=None,
            failed_at=None,
            last_error=None,
            metadata=None,
            object="thread.run.step",
            run_id="run_PTbxCaHf9XLXvcK5kFkUNDKb",
            status="completed",
            step_details=ToolCallsStepDetails(
                tool_calls=[
                    RetrievalToolCall(
                        id="call_KUnXqzDP47t078PsyviJtt5t",
                        retrieval={},
                        type="retrieval",
                    )
                ],
                type="tool_calls",
            ),
            thread_id="thread_Yw9AKdgjsQ5WjEKnXAL5NhBC",
            type="tool_calls",
            expires_at=None,
        ),
    ],
    object="list",
    first_id="step_ZtjkTzVJzfcCTlbYkBeTFrdQ",
    last_id="step_bbfaNruNeiEJTbWUvwdbesKL",
    has_more=False,
)
